//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;
    
    /// <summary>
    /// The `Status` type defines a logical error model
    /// </summary>
    public class Error
    {

        /// <summary>
        /// A developer-facing error message.
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        /// <summary>
        /// The HTTP status code
        /// </summary>
        [JsonProperty("status_code")]
        public int StatusCode { get; set; } = default!;
    }
}